# Use root/example as user/password credentials

services:
  db:
    image: mysql:9.2.0
    # NOTE: use of "mysql_native_password" is not recommended: https://dev.mysql.com/doc/refman/8.0/en/upgrading-from-previous-series.html#upgrade-caching-sha2-password
    # (this is just an example, not intended to be a production configuration)
    volumes:
      - /path/to/mysql/data:/var/lib/mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: example
    ports:
      - 3306:3306

  # navicat
  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
